name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      uses: bahmutov/npm-install@v1
      with:
       useLockFile: false
    - name: build mainnet
      run: |
        npm run build:mainnet
    - name: bot test
      run: |
        npm run bot:test
      env:
        CI: true

